default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: localuser
  password: localuser


development:
  <<: *default
  database: manga_dwnldr_development

test:
  <<: *default
  database: manga_dwnldr_test


production:
  <<: *default
  database: manga_dwnldr
